// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqopvazfiwjczciycjas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xb3B2YXpmaXdqY3pjaXljamFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDg3NDQsImV4cCI6MjA3NDU4NDc0NH0._1RFM3f3EzN-KkuDYJMkpIMjEh18j2GVIw_ilLx-2z4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});